version: '3.8'

services:
  # react-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: react-app
  #   depends_on:
  #     - nginx
   web:
    build: .
    ports:
      - "80:80"
    container_name: react-nginx-app

    restart: always
